services:
  - type: web
    name: assistania
    env: node
    buildCommand: corepack enable && yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: OPENAI_API_KEY
        value: YOUR-OPENAI-KEY-HERE
